{% set name = "shimmy" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/Farama-Foundation/Shimmy/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3ddbe2f813ef177058ab861871829e434da571d06379efe21d5aa8081afb728f
  patches:
    - 0001-skip-render-check-in-atari-test.patch

build:
  noarch: python
  number: 0

# Maybe need these up here for conda-smithy to handle them properly.
requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.18.0
    - gymnasium >=0.27.0

outputs:
  - name: {{ name|lower }}
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      build:
        - python >=3.7
      host:
        - python >=3.7
        - pip
        - gymnasium >=0.27.0
        - cloudpickle
        - jax-jumpy
        - numpy >=1.18.0
        - typing-extensions
      run:
        - python >=3.7
        - numpy >=1.18.0
        - gymnasium >=0.27.0
    test:
      imports:
        - {{ name|lower }}

  - name: {{ name|lower }}-all
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('shimmy-gym', exact=True) }}
        - {{ pin_subpackage('shimmy-atari', exact=True) }}
        # see below
        # - {{ pin_subpackage('shimmy-imageio', exact=True) }}
        # see below
        # - {{ pin_subpackage('shimmy-dm-control', exact=True) }}
        # see below
        # - {{ pin_subpackage('shimmy-dm-control-multi-agent', exact=True) }}
        # see below
        # - {{ pin_subpackage('shimmy-openspiel', exact=True) }}
        # see below
        # - {{ pin_subpackage('shimmy-meltingpot', exact=True) }}
        # see below
        # - {{ pin_subpackage('shimmy-bsuite', exact=True) }}
    test:
      imports:
        - {{ name|lower }}
      source_files:
        - tests/
      requires:
        - pytest
        - pip
      commands:
        - pip check

  - name: {{ name|lower }}-gym
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('shimmy', exact=True) }}
        - gym >=0.21
    test:
      imports:
        - {{ name|lower }}
      source_files:
        - tests/
      requires:
        - pytest
      commands:
        - pytest -v tests/test_gym.py

  - name: {{ name|lower }}-atari
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('shimmy', exact=True) }}
        - ale-py >=0.8.1,<0.9
    test:
      imports:
        - {{ name|lower }}
      source_files:
        - tests/
      requires:
        - pytest
        - pip
      commands:
        - pip install --no-cache-dir 'autorom[accept-rom-license]>=0.6.1'
        - pytest -v tests/test_atari.py

  - name: {{ name|lower }}-imageio
    build:
      # not sure if the name should be shimmy-imageio or rather shimmy-mujoco
      skip: true
      noarch: python
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('shimmy', exact=True) }}
        - mujoco-python >=2.2.0,<2.4
        - imageio >=2.14.1
    test:
      imports:
        # There are no tests in the source code for shimmy-imageio or shimmy-mujoco

  - name: {{ name|lower }}-dm-control
    build:
      # latest version of dm-control is 1.0.9 on conda-forge currently
      skip: true
      noarch: python
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('shimmy', exact=True) }}
        - dm-control >=1.0.10
        - imageio
        - h5py >=3.7.0
    test:
      imports:
        - {{ name|lower }}
      source_files:
        - tests/
      requires:
        - pytest
      commands:
        - pytest -v tests/test_dm_control.py

  - name: {{ name|lower }}-dm-control-multi-agent
    build:
      # pettingzoo is not yet available on conda-forge
      # latest version of dm-control is 1.0.9 on conda-forge currently
      skip: true
      noarch: python
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('shimmy', exact=True) }}
        - dm-control >=1.0.10
        - pettingzoo >=1.22.4
    test:
      imports:
        - {{ name|lower }}
      source_files:
        - tests/
      requires:
        - pytest
      commands:
        - pytest -v tests/test_dm_control_multi_agent.py

  - name: {{ name|lower }}-openspiel
    build:
      # open_spiel and pettingzoo are not yet available on conda-forge
      skip: true
      noarch: python
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('shimmy', exact=True) }}
        - open_spiel >=1.2
        - pettingzoo >=1.22.4
    test:
      imports:
        - {{ name|lower }}
      source_files:
        - tests/
      requires:
        - pytest
      commands:
        - pytest -v tests/test_openspiel.py

  - name: {{ name|lower }}-meltingpot
    build:
      # pettingzoo is not yet available on conda-forge
      skip: true
      noarch: python
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('shimmy', exact=True) }}
        - pettingzoo >=1.22.4
    test:
      imports:
        - {{ name|lower }}
      source_files:
        - tests/
      requires:
        - pytest
        # test will be skipped without meltingpot, but it is not yet available on conda-forge
        # - meltingpot
      commands:
        - pytest -v tests/test_meltingpot.py

  - name: {{ name|lower }}-bsuite
    build:
      # bsuite is not yet available on conda-forge
      skip: true
      noarch: python
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('shimmy', exact=True) }}
        - bsuite >=0.3.5
    test:
      imports:
        - {{ name|lower }}
      source_files:
        - tests/
      requires:
        - pytest
      commands:
        - pytest -v tests/test_bsuite.py

about:
  home: https://github.com/Farama-Foundation/Shimmy
  summary: API for converting popular non-gymnasium environments to a gymnasium compatible environment.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
