{% set name = "shimmy" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Shimmy-{{ version }}.tar.gz
  sha256: 7b96915445ee5488dcb19ccf52ce5581d6f00cc5cf0e0dff36b16cd65bffcb75

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.18.0
    - gymnasium >=0.26.0

test:
  imports:
    - shimmy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Farama-Foundation/Shimmy
  summary: API for converting popular non-gymnasium environments to a gymnasium compatible environment.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
